apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubevirtprojects.clusterview.open-cluster-management.io
spec:
  group: clusterview.open-cluster-management.io
  names:
    kind: Project
    listKind: KubevirtprojectList
    plural: kubevirtprojects
    singular: kubevirtproject
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - metadata
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
      additionalPrinterColumns:
        - name: Cluster
          type: string
          jsonPath: .metadata.labels['cluster']
        - name: Project
          type: string
          jsonPath: .metadata.labels['project']
