apiVersion: v1
kind: Service
metadata:
  name: mtv-advisor-service
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: mtv-integrations
    component: "ocm-mtv-integrations-ctrl"
  ports:
    - name: advisor-http
      protocol: TCP
      port: 8082
      targetPort: advisor-http
