apiVersion: rbac.open-cluster-management.io/v1alpha1
kind: ClusterPermission
metadata:
  name: kubevirt-admin
  namespace: bm14
spec:
  clusterRoleBinding:
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: kubevirt.io:admin
    subject:
      kind: Group
      name: system:cluster-admins
      apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.open-cluster-management.io/v1alpha1
kind: ClusterPermission
metadata:
  name: kubevirt-admin
  namespace: local-cluster
spec:
  clusterRoleBinding:
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: kubevirt.io:admin
    subject:
      kind: Group
      name: system:cluster-admins
      apiGroup: rbac.authorization.k8s.io
