name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Running Tests
        run: |
          go mod tidy
          make test
      - name: Upload unit test artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: artifacts-unit
          path: |
            coverage_unit.out
            report_unit.json
          if-no-files-found: ignore
  webhook-test:
    runs-on: ubuntu-latest
    env:
      KIND_NAME: kind-cluster
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Running Tests
        run: |
          openssl version
          export CONTAINER_TOOL=docker
          make prepare-webhook-test
          make run-webhook-test
      - name: Upload webhook test artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: artifacts-webhook
          path: |
            report_webhook.json
          if-no-files-found: ignore
  provider-crd-test:
    runs-on: ubuntu-latest
    env:
      KIND_NAME: kind-cluster
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Running Tests
        run: |
          make prepare-e2e-test
          make run-provider-crd-test
      - name: Upload provider CRD artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: artifacts-provider-crd
          path: |
            coverage_e2e.out
            report_e2e.json
          if-no-files-found: ignore

  e2e-test:
    runs-on: ubuntu-latest
    env:
      KIND_NAME: kind-cluster
    steps:
      - name: Clone the code
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Running Tests
        run: |
          make prepare-e2e-test
          make run-e2e-test
      - name: Upload e2e test artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: artifacts-e2e
          path: |
            coverage_e2e.out
            report_e2e.json
          if-no-files-found: ignore
  sonarcloud:
    runs-on: ubuntu-latest
    needs:
      - e2e-test
      - webhook-test
      - test
      - provider-crd-test
    steps:
      - run: echo "Running SonarCloud analysis..."
      - name: Download test artifacts
        uses: actions/download-artifact@v8
        with:
          pattern: artifacts-*
          merge-multiple: true
          path: artifacts
      - name: Upload artifacts for the sonarcloud workflow
        uses: actions/upload-artifact@v7
        with:
          name: artifacts
          path: |
            artifacts/coverage*.out
            artifacts/report*.json
          if-no-files-found: error
