name: Push image to quay.io registry

on:
  push:
    branches:
      - main
jobs:
  test:
    name: Push image to OpenShift registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR safely
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get -y install podman

      - name: Push image to registry
        env:
          REGISTRY: quay.io
          USERNAME: ${{ secrets.QUAY_USERNAME }}
          PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        run: |
          go mod tidy
          if [[ -z "$USERNAME" || -z "$PASSWORD" ]]; then
            echo "❌ QUAY_USERNAME or QUAY_PASSWORD is not set"
            exit 1
          fi
          echo "Logging in to $REGISTRY with username $USERNAME"
          podman login --username "$USERNAME" -p "$PASSWORD" --tls-verify=false "$REGISTRY"
          IMAGE_NAME=run-${{ github.run_id }}
          IMAGE=quay.io/stolostron-vm/$IMAGE_NAME:latest
          echo "\033[0;32mYour image name is $IMAGE_NAME\033[0m" 
          podman build --platform linux/amd64 -t $IMAGE .
          podman push $IMAGE
